<?php echo $this->doctype(); ?>

<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <?php echo $this->headMeta()
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ->appendName('viewport', 'width=device-width, initial-scale=1.0');
    ?>

    <?php echo $this->headTitle('Web Application')->setSeparator(' - ')->setAutoEscape(false); ?>

    <!-- styles -->
    <?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favicon.ico'])
        //->prependStylesheet($this->basePath('assets/bootstrap-3.3.7/css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('assets/bootstrap-3.3.7/css/bootstrap.min.css'));
    ?>

</head>
<body>

<div class="container">

    <div class="row">
        <div class="col-md-12">
            <?php echo $this->content; ?>

        </div>
    </div>

</div>

<!-- Scripts -->
<?php echo $this->headScript()
    //->prependFile($this->basePath('assets/bootstrap-3.3.7/js/bootstrap.min.js'))
    ->prependFile($this->basePath('assets/jquery-3.2.1/jquery-3.2.1.min.js'));
?>

<?php echo $this->inlineScript(); ?>

</body>
</html>
